import { build } from "esbuild";
import { fileURLToPath } from "url";
import { writeFileSync } from "fs";
import { dirname, join } from "path";
import { algoFingerprint, scoutFingerprint } from "./algo-fingerprint.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const fingerprint = algoFingerprint();
const scout = scoutFingerprint();

// Emitted as a real source file rather than injected as a build-time define.
//
// The define worked for the API bundles (built here, where the api/*.ts
// sources exist) but NOT for the frontend: .vercelignore excludes api/**/*.ts,
// so Vercel's builder cannot read the files the hash is computed from. The
// frontend therefore fell back to "dev" in production, and the hash a user
// could read in the patch notes was not the hash attached to their feedback.
//
// Writing it to disk here means it is computed once, locally, where the inputs
// exist, and both builds consume the same committed value. `npm run build:api`
// is already a mandatory pre-deploy step, so there is nothing new to remember.
//
// Deliberately NOT under src/algo/: that directory is an input to the hash, so
// a generated file there would change the hash it just recorded.
writeFileSync(
  join(root, "src/algoFingerprint.generated.ts"),
  `// GENERATED by scripts/build-api.mjs. Do not edit by hand.\n` +
    `// Content hash of every file that decides which trades get suggested and\n` +
    `// how they are explained. Commit it: the deployed frontend reads it.\n` +
    `export const ALGO_FINGERPRINT_BUILD = "${fingerprint}";\n` +
    `\n` +
    `// The scouting report (src/algo/plays.ts) hashed on its own, so a change to\n` +
    `// a play does not read as a change to the trade engine. Stamped on play\n` +
    `// feedback only.\n` +
    `export const SCOUT_FINGERPRINT_BUILD = "${scout}";\n`,
);

const entries = [
  "api/leagues/sync.ts",
  "api/leagues/overview.ts",
  "api/leagues/trades.ts",
  "api/trades/find.ts",
  "api/trades/probe.ts",
  "api/user/leagues.ts",
  "api/feedback.ts",
  "api/admin/users.ts",
];

await Promise.all(
  entries.map((entry) =>
    build({
      entryPoints: [join(root, entry)],
      bundle: true,
      platform: "node",
      target: "node20",
      format: "cjs",
      packages: "external",
      outfile: join(root, entry.replace(/\.ts$/, ".js")),
    }),
  ),
);

console.log(`API bundles built (algo fingerprint ${fingerprint}, scout ${scout})`);
