// GENERATED by scripts/build-api.mjs. Do not edit by hand.
// Content hash of every file that decides which trades get suggested and
// how they are explained. Commit it: the deployed frontend reads it.
export const ALGO_FINGERPRINT_BUILD = "530ce0f18047";

// The scouting report (src/algo/plays.ts) hashed on its own, so a change to
// a play does not read as a change to the trade engine. Stamped on play
// feedback only.
export const SCOUT_FINGERPRINT_BUILD = "06d7fc6fdd55";
