// Privacy policy and terms of service.
//
// IMPORTANT: this is plain-language boilerplate written to describe what the
// app actually does. It has NOT been reviewed by a lawyer. It is honest, which
// is the part that matters most for a personal app with a handful of users,
// but it is not a substitute for legal advice if this ever grows.
//
// If you change what the app collects or which third parties it talks to,
// change this too. A privacy policy that has drifted from reality is worse
// than none, because it is a false statement rather than a missing one.

export type LegalSection = { heading: string; body: string[] };

export const LEGAL_UPDATED = "2026-07-25";

export const PRIVACY_POLICY: LegalSection[] = [
  {
    heading: "The short version",
    body: [
      "Send It is a personal project run for a small group of friends. It is not a business, there is nothing to buy, and your data is not sold, rented, or shared with advertisers. There are no ads and no tracking pixels.",
    ],
  },
  {
    heading: "What is collected",
    body: [
      "When you sign in with Google, we receive your email address and your Google account identifier. We do not receive or store your Google password.",
      "When you connect a league, we store your Sleeper username and league IDs, and we fetch and cache public Sleeper data for that league: rosters, league settings, draft picks, and trade history. This is the same data anyone can read from Sleeper's public API.",
      "When you leave feedback on a trade, we store your verdict, any reasons you select, your comment, the trade package you were looking at, the engine scores behind it, and the exact prompt used to write the rationale. Your user ID and email are attached so we can tell distinct users apart.",
      "Basic server logs are produced by our host as a side effect of serving the site.",
    ],
  },
  {
    heading: "What it is used for",
    body: [
      "Running the app: signing you in, showing your leagues, and generating trades.",
      "Improving the algorithm. Feedback is the only tuning signal this app has, and it is read directly by the person building it.",
      "Nothing else. There is no profiling, no advertising, and no resale.",
    ],
  },
  {
    heading: "Who else sees it",
    body: [
      "Google Firebase handles sign-in and stores the database.",
      "Vercel hosts the site and runs the server code.",
      "Sleeper and FantasyCalc provide league data and player values. We read from them; we do not send them anything about you.",
      "Anthropic's API writes the trade rationales. The text sent contains player names, team names, and engine numbers. It does not contain your email, your account ID, or anything else that identifies you.",
      "That is the complete list.",
    ],
  },
  {
    heading: "Retention and deletion",
    body: [
      "Data is kept for as long as the app runs, because trade feedback loses its value if it cannot be compared across engine versions.",
      "You can ask for your account and its data to be deleted, and it will be. Ask the person who gave you access.",
    ],
  },
  {
    heading: "Children",
    body: [
      "Access is granted manually to people known to the operator. The app is not directed at children under 13 and is not intended for them.",
    ],
  },
  {
    heading: "Changes",
    body: [
      "If what we collect changes, this page changes with it, and the date at the top moves. Meaningful changes will also appear in the release notes.",
    ],
  },
];

export const TERMS_OF_SERVICE: LegalSection[] = [
  {
    heading: "What this is",
    body: [
      "Send It is a free, personal dynasty fantasy football tool provided as-is to a small invited group. Access is granted manually and can be revoked at any time, for any reason, without notice.",
    ],
  },
  {
    heading: "This is not advice",
    body: [
      "Everything here is an opinion generated by math and by a language model, about a game. Player values come from a third party, the algorithm reflects deliberate judgment calls that are documented and frequently wrong, and the written rationales are produced by an AI that can be confidently mistaken.",
      "Nothing on this site is financial, investment, betting, or professional advice of any kind. Trades you make are your own decisions and your own responsibility.",
    ],
  },
  {
    heading: "No guarantees",
    body: [
      "The service is provided without warranty of any kind. It may be wrong, unavailable, slow, or discontinued entirely. Data may be lost. The algorithm changes often and without notice, and a trade suggested today may not be suggested tomorrow. That is the point of the release notes, not a defect.",
      "To the fullest extent permitted by law, the operator is not liable for any loss arising from your use of the service.",
    ],
  },
  {
    heading: "Fair use",
    body: [
      "Do not use the service to break the law, to abuse or harass anyone, to attack the site or its infrastructure, or to scrape it in bulk.",
      "Do not share your access with people who have not been granted it.",
    ],
  },
  {
    heading: "Other people's data",
    body: [
      "League data covers everyone in your league, not just you. Treat what you see about other managers the way you would want yours treated.",
    ],
  },
  {
    heading: "Ownership",
    body: [
      "The site, its code, and its algorithm belong to the operator. League and player data belong to their respective sources: Sleeper, FantasyCalc, and the NFL.",
    ],
  },
  {
    heading: "Changes",
    body: [
      "These terms can change. Continuing to use the app after a change means you accept it.",
    ],
  },
];
